[package]
name = "libfm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
magnus = { version = "0.4", features = ["rb-sys-interop"] }
rb-sys = { version = "0.9", features = ["ruby-macros"] }
winit = "0.27"
crossbeam-channel = "0.5.6"
image = "0.24"
enum-as-inner = "0.5.1"
glutin = "0.30.1"
glutin-winit = "0.2.1"
glow = "0.11.2"
raw-window-handle = "0.5.0"
once_cell = "1.16.0"