[package]
name = "screen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ron = "0.8"
serde = "1.0"
winit = "0.27"
image = "0.24"
wgpu = "0.14"
bytemuck = "1.13"
pollster = "0.2"
